---
- ansible.builtin.import_tasks: setup.yml
  tags: caddy.setup

- ansible.builtin.include_tasks: vhosts.yml
  tags: caddy.vhosts
  vars:
    vhost: "{{ caddy_vhost_defaults | combine(vhost_) }}"
  loop: "{{ caddy_vhosts }}"
  loop_control:
    loop_var: vhost_
