---
- name: Upload caddy binary
  ansible.builtin.copy:
    src: "{{ caddy_src_bin }}"
    dest: "{{ caddy_bin_path }}"
    mode: "0755"
  notify: caddy restart

- name: Add caddy group
  ansible.builtin.group:
    name: "{{ caddy_group_name }}"
    gid: "{{ caddy_group_id }}"

- name: Add caddy user
  ansible.builtin.user:
    name: "{{ caddy_user_name }}"
    uid: "{{ caddy_user_id }}"
    group: "{{ caddy_group_id }}"
    home: "{{ caddy_user_home_dir }}"
    create_home: true
    shell: "/usr/sbin/nologin"
    system: true

- name: Create Caddy systemd unit file
  ansible.builtin.template:
    src: caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    mode: "0644"
  notify: service modified

- name: Create config directory
  ansible.builtin.file:
    path: "{{ caddy_config_path }}"
    state: directory
    mode: "0755"

- name: Create snippets directory
  ansible.builtin.file:
    path: "{{ caddy_config_path }}/snippets"
    state: directory
    mode: "0755"

- name: Create vhosts directory
  ansible.builtin.file:
    path: "{{ caddy_config_path }}/vhosts"
    state: directory
    mode: "0755"

- name: Create log directory
  ansible.builtin.file:
    path: "{{ caddy_log_path }}"
    state: directory
    mode: "0755"
    owner: caddy

- name: Add Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ caddy_config_path }}/Caddyfile"
    mode: "0644"
  notify: caddy reload

- name: Copy TLS config snippet
  ansible.builtin.template:
    mode: "0644"
    src: tls.conf.j2
    dest: "{{ caddy_config_path }}/snippets/tls.conf"
  notify: caddy reload

- name: Enable and start Caddy service
  ansible.builtin.service:
    name: caddy.service
    state: started
    enabled: true
