---
- name: Upload caddy binary
  copy:
    src: bin/caddy
    dest: '{{ caddy_bin_path }}'
    mode: '0755'

# - name: Install setcap
#   apt:
#     name: libcap2-bin

# - name: Set capability on the caddy binary file to be able to bind to TCP port <1024
#   capabilities:
#     path: '{{ caddy_bin_path }}'
#     capability: cap_net_bind_service+ep

- name: Add caddy group
  group:
    name: '{{ caddy_group_name }}'
    gid: '{{ caddy_group_id }}'

- name: Add caddy user
  user:
    name: '{{ caddy_user_name }}'
    uid: '{{ caddy_user_id }}'
    group: '{{ caddy_group_id }}'
    home: '{{ caddy_user_home_dir }}'
    create_home: true
    shell: '/usr/sbin/nologin'
    system: true

- name: Create Caddy systemd unit file
  template:
    src: caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    mode: 0644
  notify: service modified

- name: Create config directory
  file:
    path: '{{ caddy_config_path }}'
    state: directory
    owner: caddy
    group: caddy

- name: Create snippets directory
  file:
    path: '{{ caddy_config_path }}/snippets'
    state: directory
    owner: caddy
    group: caddy

- name: Create vhosts directory
  file:
    path: '{{ caddy_config_path }}/vhosts'
    state: directory
    owner: caddy
    group: caddy

- name: Create log directory
  file:
    path: '{{ caddy_log_path }}'
    state: directory
    owner: '{{ caddy_user_name }}'
    group: '{{ caddy_user_name }}'

- name: Add Caddyfile
  copy:
    src: Caddyfile
    dest: '{{ caddy_config_path }}/Caddyfile'
    owner: caddy
    group: caddy
    mode: 0644
  notify: caddy reload

- name: Copy TLS config snippet
  template:
    owner: caddy
    group: caddy
    mode: 0644
    src: tls.conf.j2
    dest: '{{ caddy_config_path }}/snippets/tls.conf'
  notify: caddy reload

- name: Enable and start Caddy service
  service:
    name: caddy.service
    state: started
    enabled: true
