---
- name: Add vhost
  ansible.builtin.template:
    src: "{{ vhost.template }}"
    dest: "{{ caddy_config_path }}/vhosts/{{ vhost.name }}"
    mode: "0644"
  notify: Reload caddy
  tags: caddy.vhosts
