---
- name: caddy reload
  ansible.builtin.service:
    name: caddy
    state: reloaded

- name: caddy restart
  listen: service modified
  ansible.builtin.service:
    name: caddy
    state: restarted

- name: systemctl daemon-reload
  listen: service modified
  ansible.builtin.service:
    daemon_reload: true
