---
- name: Reload caddy
  ansible.builtin.service:
    name: caddy
    state: reloaded

- name: Restart caddy
  listen: service modified
  ansible.builtin.service:
    name: caddy
    state: restarted

- name: Run systemctl daemon-reload
  listen: service modified
  ansible.builtin.systemd:
    daemon_reload: true
