---

- name: caddy reload
  service:
    name: caddy
    state: reloaded

- name: caddy restart
  listen: service modified
  service:
    name: caddy
    state: restarted

- name: systemctl daemon-reload
  listen: service modified
  service:
    daemon_reload: true
